

excepted_filenames = [
    "MEGA",
    "Ukategorisert",
    "Tekst",
    "Programmering",
    "Annet",
    "Media",
    ".DS_Store",
    "SkrivebordsRydder",
    "Sky"
]

spesific_filehandling = [
    "Skjermbilde"
]

extensions_folders = {
#No name
    "noname" : "/Users/Dag/Desktop/Ukategorisert",
    "Folder" : "/Users/Dag/Desktop/Ukategorisert/Mapper",
#Exceptions
    "Skjermbilde" : "/Users/Dag/Desktop/Media/Skjermbilder",
#Sublime
    ".sublime-project" : "/Users/Dag/Desktop/Programmering/Sublime Projects",
    ".sublime-workspace" : "/Users/Dag/Desktop/Programmering/Sublime Projects",
#Audio
    ".aif" : "/Users/Dag/Desktop/Media/Lyd",
    ".cda" : "/Users/Dag/Desktop/Media/Lyd",
    ".mid" : "/Users/Dag/Desktop/Media/Lyd",
    ".midi" : "/Users/Dag/Desktop/Media/Lyd",
    ".mp3" : "/Users/Dag/Desktop/Media/Lyd",
    ".mpa" : "/Users/Dag/Desktop/Media/Lyd",
    ".ogg" : "/Users/Dag/Desktop/Media/Lyd",
    ".wav" : "/Users/Dag/Desktop/Media/Lyd",
    ".wma" : "/Users/Dag/Desktop/Media/Lyd",
    ".wpl" : "/Users/Dag/Desktop/Media/Lyd",
    ".m3u" : "/Users/Dag/Desktop/Media/Lyd",
#Text
    ".txt" : "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".doc" : "/Users/Dag/Desktop/Tekst/Word",
    ".docx" : "/Users/Dag/Desktop/Tekst/Word",
    ".odt " : "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".pdf": "/Users/Dag/Desktop/Tekst/PDF",
    ".rtf": "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".tex": "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".wks ": "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".wps": "/Users/Dag/Desktop/Tekst/TekstFiles",
    ".wpd": "/Users/Dag/Desktop/Tekst/TekstFiles",
#Video
    ".3g2": "/Users/Dag/Desktop/Media/Video",
    ".3gp": "/Users/Dag/Desktop/Media/Video",
    ".avi": "/Users/Dag/Desktop/Media/Video",
    ".flv": "/Users/Dag/Desktop/Media/Video",
    ".h264": "/Users/Dag/Desktop/Media/Video",
    ".m4v": "/Users/Dag/Desktop/Media/Video",
    ".mkv": "/Users/Dag/Desktop/Media/Video",
    ".mov": "/Users/Dag/Desktop/Media/Video",
    ".mp4": "/Users/Dag/Desktop/Media/Video",
    ".mpg": "/Users/Dag/Desktop/Media/Video",
    ".mpeg": "/Users/Dag/Desktop/Media/Video",
    ".rm": "/Users/Dag/Desktop/Media/Video",
    ".swf": "/Users/Dag/Desktop/Media/Video",
    ".vob": "/Users/Dag/Desktop/Media/Video",
    ".wmv": "/Users/Dag/Desktop/Media/Video",
#Images
    ".ai": "/Users/Dag/Desktop/Media/Bilder",
    ".bmp": "/Users/Dag/Desktop/Media/Bilder",
    ".gif": "/Users/Dag/Desktop/Media/Bilder",
    ".ico": "/Users/Dag/Desktop/Media/Bilder",
    ".jpg": "/Users/Dag/Desktop/Media/Bilder",
    ".jpeg": "/Users/Dag/Desktop/Media/Bilder",
    ".png": "/Users/Dag/Desktop/Media/Bilder",
    ".ps": "/Users/Dag/Desktop/Media/Bilder",
    ".psd": "/Users/Dag/Desktop/Media/Bilder",
    ".svg": "/Users/Dag/Desktop/Media/Bilder",
    ".tif": "/Users/Dag/Desktop/Media/Bilder",
    ".tiff": "/Users/Dag/Desktop/Media/Bilder",
    ".CR2": "/Users/Dag/Desktop/Media/Bilder",
#Internet
    ".asp": "/Users/Dag/Desktop/Annet/Internet",
    ".aspx": "/Users/Dag/Desktop/Annet/Internet",
    ".cer": "/Users/Dag/Desktop/Annet/Internet",
    ".cfm": "/Users/Dag/Desktop/Annet/Internet",
    ".cgi": "/Users/Dag/Desktop/Annet/Internet",
    ".pl": "/Users/Dag/Desktop/Annet/Internet",
    ".css": "/Users/Dag/Desktop/Annet/Internet",
    ".htm": "/Users/Dag/Desktop/Annet/Internet",
    ".js": "/Users/Dag/Desktop/Annet/Internet",
    ".jsp": "/Users/Dag/Desktop/Annet/Internet",
    ".part": "/Users/Dag/Desktop/Annet/Internet",
    ".php": "/Users/Dag/Desktop/Annet/Internet",
    ".rss": "/Users/Dag/Desktop/Annet/Internet",
    ".xhtml": "/Users/Dag/Desktop/Annet/Internet",
#Compressed
    ".7z": "/Users/Dag/Desktop/Annet/Compressed",
    ".arj": "/Users/Dag/Desktop/Annet/Compressed",
    ".deb": "/Users/Dag/Desktop/Annet/Compressed",
    ".pkg": "/Users/Dag/Desktop/Annet/Compressed",
    ".rar": "/Users/Dag/Desktop/Annet/Compressed",
    ".rpm": "/Users/Dag/Desktop/Annet/Compressed",
    ".tar.gz": "/Users/Dag/Desktop/Annet/Compressed",
    ".z": "/Users/Dag/Desktop/Annet/Compressed",
    ".zip": "/Users/Dag/Desktop/Annet/Compressed",
#Disc
    ".bin": "/Users/Dag/Desktop/Annet/Disc",
    ".dmg": "/Users/Dag/Desktop/Annet/Disc",
    ".iso": "/Users/Dag/Desktop/Annet/Disc",
    ".toast": "/Users/Dag/Desktop/Annet/Disc",
    ".vcd": "/Users/Dag/Desktop/Annet/Disc",
#Data
    ".csv": "/Users/Dag/Desktop/Programmering/Database",
    ".dat": "/Users/Dag/Desktop/Programmering/Database",
    ".db": "/Users/Dag/Desktop/Programmering/Database",
    ".dbf": "/Users/Dag/Desktop/Programmering/Database",
    ".log": "/Users/Dag/Desktop/Programmering/Database",
    ".mdb": "/Users/Dag/Desktop/Programmering/Database",
    ".sav": "/Users/Dag/Desktop/Programmering/Database",
    ".sql": "/Users/Dag/Desktop/Programmering/Database",
    ".tar": "/Users/Dag/Desktop/Programmering/Database",
    ".xml": "/Users/Dag/Desktop/Programmering/Database",
    ".json": "/Users/Dag/Desktop/Programmering/Database",
#Executables
    ".apk": "/Users/Dag/Desktop/Annet/Executables",
    ".bat": "/Users/Dag/Desktop/Annet/Executables",
    ".com": "/Users/Dag/Desktop/Annet/Executables",
    ".exe": "/Users/Dag/Desktop/Annet/Executables",
    ".gadget": "/Users/Dag/Desktop/Annet/Executables",
    ".jar": "/Users/Dag/Desktop/Annet/Executables",
    ".wsf": "/Users/Dag/Desktop/Annet/Executables",
#Fonts
    ".fnt": "/Users/Dag/Desktop/Annet/Fonts",
    ".fon": "/Users/Dag/Desktop/Annet/Fonts",
    ".otf": "/Users/Dag/Desktop/Annet/Fonts",
    ".ttf": "/Users/Dag/Desktop/Annet/Fonts",
#Presentations
    ".key": "/Users/Dag/Desktop/Tekst/Presentasjoner",
    ".odp": "/Users/Dag/Desktop/Tekst/Presentasjoner",
    ".pps": "/Users/Dag/Desktop/Tekst/Presentasjoner",
    ".ppt": "/Users/Dag/Desktop/Tekst/Presentasjoner",
    ".pptx": "/Users/Dag/Desktop/Tekst/Presentasjoner",
#Programmering
    ".c": "/Users/Dag/Desktop/Programmering/C&C++",
    ".class": "/Users/Dag/Desktop/Programmering/Java",
    ".dart": "/Users/Dag/Desktop/Programmering/Dart",
    ".py": "/Users/Dag/Desktop/Programmering/Python",
    ".sh": "/Users/Dag/Desktop/Programmering/Shell",
    ".swift": "/Users/Dag/Desktop/Programmering/Swift",
    ".html": "/Users/Dag/Desktop/Programmering/C&C++",
    ".h": "/Users/Dag/Desktop/Programmering/C&C++",
#Spreadsheets
    ".ods" : "/Users/Dag/Desktop/Tekst/Excel",
    ".xlr" : "/Users/Dag/Desktop/Tekst/Excel",
    ".xls" : "/Users/Dag/Desktop/Tekst/Excel",
    ".xlsx" : "/Users/Dag/Desktop/Tekst/Excel",
#System
    ".bak" : "/Users/Dag/Desktop/Tekst/Andre",
    ".cab" : "/Users/Dag/Desktop/Tekst/Andre",
    ".cfg" : "/Users/Dag/Desktop/Tekst/Andre",
    ".cpl" : "/Users/Dag/Desktop/Tekst/Andre",
    ".cur" : "/Users/Dag/Desktop/Tekst/Andre",
    ".dll" : "/Users/Dag/Desktop/Tekst/Andre",
    ".dmp" : "/Users/Dag/Desktop/Tekst/Andre",
    ".drv" : "/Users/Dag/Desktop/Tekst/Andre",
    ".icns" : "/Users/Dag/Desktop/Tekst/Andre",
    ".ico" : "/Users/Dag/Desktop/Tekst/Andre",
    ".ini" : "/Users/Dag/Desktop/Tekst/Andre",
    ".lnk" : "/Users/Dag/Desktop/Tekst/Andre",
    ".msi" : "/Users/Dag/Desktop/Tekst/Andre",
    ".sys" : "/Users/Dag/Desktop/Tekst/Andre",
    ".tmp" : "/Users/Dag/Desktop/Tekst/Andre",
}